name: minha_busca_Atak
description: "Este aplicativo permite ao seu usuário fazer uma busca na internet e ter os resultados do Google de forma simplificada, com o título e link de cada resultado"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_bloc: ^8.1.5
  sqflite: ^2.3.2
  path_provider: ^2.0.2
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.13.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/logo-atak-sistemas.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/